version: "3"
services:
  client:
    image: "abhijitshaw99/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "abhijitshaw99/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_TLS=$REDIS_TLS
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "abhijitshaw99/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_TLS=$REDIS_TLS
  nginx:
    image: "abhijitshaw99/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
